export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || '/api/football'

export const ENDPOINTS = {
  matches: `/matches`,
  matchesLive: `/matches/live`,
  matchesFeatured: `/matches/featured`,
  matchById: (id: number | string) => `/matches/${id}`,
  matchStats: (id: number | string) => `/matches/${id}/stats`,
  matchH2h: (id: number | string) => `/matches/${id}/h2h`,
  matchLineups: (id: number | string) => `/matches/${id}/lineups`,
  matchPreStats: (id: number | string) => `/matches/${id}/pre-stats`,
  matchTips: (id: number | string) => `/matches/${id}/tips`,
  matchTrends: (id: number | string) => `/matches/${id}/trends`,
  matchPredictions: (id: number | string) => `/matches/${id}/predictions`,
  matchTimeline: (id: number | string) => `/matches/${id}/timeline`,
  matchSuggestions: (id: number | string) => `/matches/${id}/suggestions`,
  standings: `/standings`,
  brackets: `/brackets`,
  history: `/history`,
  historyStats: `/history/stats`,
  historyBySeason: (seasonNum: number) => `/history/${seasonNum}`,
  historyMatchStats: (seasonNum: number) => `/history/${seasonNum}/match-stats`,
  historyMatchLineup: (seasonNum: number) => `/history/${seasonNum}/match-overview`,
  statsScorers: `/stats/scorers`,
  statsAssists: `/stats/assists`,
  statsRatings: `/stats/ratings`,
  statsTeamOfWeek: `/stats/team-of-week`,
  trends: `/trends`,
  news: `/news`,
  newsByGame: (id: number | string) => `/news/game/${id}`,
  athletes: `/athletes`,
  athleteById: (id: number | string) => `/athletes/${id}`,
  athleteCareer: (id: number | string) => `/athletes/${id}/career`,
  athleteTrophies: (id: number | string) => `/athletes/${id}/trophies`,
  athleteTransfers: (id: number | string) => `/athletes/${id}/transfers`,
  teams: `/teams`,
  teamById: (id: number | string) => `/teams/${id}`,
  teamMatches: (id: number | string) => `/teams/${id}/matches`,
  countries: `/countries`,
  tournamentInfo: `/tournament-info`,
  competitions: `/competitions`,
  competitionsFeatured: `/competitions/featured`,
  competitionById: (id: number | string) => `/competitions/${id}`,
  competitionSeasons: (id: number | string) => `/competitions/${id}/seasons`,
} as const
