export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || '/api/football'

export const ENDPOINTS = {
  matches: `${API_BASE_URL}/matches`,
  matchesLive: `${API_BASE_URL}/matches/live`,
  matchesFeatured: `${API_BASE_URL}/matches/featured`,
  matchById: (id: number | string) => `${API_BASE_URL}/matches/${id}`,
  matchStats: (id: number | string) => `${API_BASE_URL}/matches/${id}/stats`,
  matchH2h: (id: number | string) => `${API_BASE_URL}/matches/${id}/h2h`,
  matchLineups: (id: number | string) => `${API_BASE_URL}/matches/${id}/lineups`,
  matchPreStats: (id: number | string) => `${API_BASE_URL}/matches/${id}/pre-stats`,
  matchTips: (id: number | string) => `${API_BASE_URL}/matches/${id}/tips`,
  matchTrends: (id: number | string) => `${API_BASE_URL}/matches/${id}/trends`,
  matchPredictions: (id: number | string) => `${API_BASE_URL}/matches/${id}/predictions`,
  matchTimeline: (id: number | string) => `${API_BASE_URL}/matches/${id}/timeline`,
  standings: `${API_BASE_URL}/standings`,
  brackets: `${API_BASE_URL}/brackets`,
  history: `${API_BASE_URL}/history`,
  statsScorers: `${API_BASE_URL}/stats/scorers`,
  statsAssists: `${API_BASE_URL}/stats/assists`,
  statsRatings: `${API_BASE_URL}/stats/ratings`,
  statsTeamOfWeek: `${API_BASE_URL}/stats/team-of-week`,
  trends: `${API_BASE_URL}/trends`,
  news: `${API_BASE_URL}/news`,
  newsByGame: (id: number | string) => `${API_BASE_URL}/news/game/${id}`,
  athletes: `${API_BASE_URL}/athletes`,
  athleteById: (id: number | string) => `${API_BASE_URL}/athletes/${id}`,
  athleteCareer: (id: number | string) => `${API_BASE_URL}/athletes/${id}/career`,
  athleteTrophies: (id: number | string) => `${API_BASE_URL}/athletes/${id}/trophies`,
  athleteTransfers: (id: number | string) => `${API_BASE_URL}/athletes/${id}/transfers`,
  teams: `${API_BASE_URL}/teams`,
  teamById: (id: number | string) => `${API_BASE_URL}/teams/${id}`,
  teamMatches: (id: number | string) => `${API_BASE_URL}/teams/${id}/matches`,
  countries: `${API_BASE_URL}/countries`,
  tournamentInfo: `${API_BASE_URL}/tournament-info`,
} as const
